services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/app
      - /app/node_modules

    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: ticket
      POSTGRES_DATABASE: ticket
      REDIS_HOST: redis
      REDIS_PORT: 6379

    ports:
      - '8080:8080'

    networks:
      - ticket-network

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:latest
    command: [ 'postgres', '-c', 'log_statement=all' ]
    restart: always
    environment:
      POSTGRES_PASSWORD: ticket
      POSTGRES_DB: ticket

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 15s
      retries: 5

    ports:
      - '5432:5432'

    networks:
      - ticket-network

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '6379:6379'
    networks:
      - ticket-network

networks:
  ticket-network:
    driver: bridge
